### ISSUE TITLE
Segfault on exit

### ISSUE THREAD

**Issue by camertron** [jasonroelofs/rice#126]
Hey maintainers!

First off: thanks for an awesome gem! I've been playing with Rice for the past few days and really digging how easy it makes wrapping C++ types. Documentation is quite solid too. So thanks! The Ruby community is as rich as it is because of people like you :)

I'm hoping you can help me with a problem I'm having with C++/Ruby interop. I'm trying to wrap an [ANTLR](https://github.com/antlr/antlr4) parser I generated to parse the MySQL query language. ANTLR optionally generates a visitor base class which you're supposed to extend with visit_* methods. I've been able to expose the C++ base visitor class and have inherited from it in Ruby. The ruby code looks like this:

```ruby
# ruby class inheriting from C++ class
class MyVisitor < MySqlParser::MySqlVisitor
  def visit_root(ctx)
    puts 'visit_root called from rubyland!'
  end
end

visitor = MyVisitor.new
MySqlParser::Parser.new.parse('./test.sql', visitor)
puts 'done!'
```

The actual parsing logic looks like this:

```c++
VALUE mysql_parser_parse(string file, MySqlVisitor* visitor) {
  ifstream stream;
  stream.open(file);

  ANTLRInputStream input(stream);
  MySqlLexer lexer(&input);
  CommonTokenStream tokens(&lexer);
  MySqlParser parser(&tokens);
  MySqlParser::RootContext* tree = parser.root();
  visitor -> visit(tree);
  stream.close();

  return Qnil;
}
```

Running this code actually works. It prints out "visit_root called from rubyland!" and "done!" as you'd expect. Unfortunately then the program tries to exit and segfaults. Based on the stack trace it appears the offending function call is `_ZN6antlr44tree9ParseTreeD0Ev`, which I can't make heads or tails of. If I instead allocate `CommonTokenStream` and `MySqlParser` on the heap (i.e. with `new`), no segfault occurs. It's as if Ruby is trying to free resources it didn't allocate and has no ownership of.

Any ideas? Here's the code: https://github.com/camertron/mysql-parser-rb

**Comment by jasonroelofs** [comment]
Your guess as to what's going on is probably correct. If possible can you make a gist of the segfault stack trace? I'm wondering which object it's trying to free. By default. Rice tends to wrap C++ objects in a way that takes ownership of those objects. This logic is done in the set of `to_ruby<>` template methods. It's possible that the culprit is the "RootContext", as that looks like an object that's probably created by ANTLR and not Ruby, so you'd need to add the following:

```
// Store the RootContext wrapper object here so we can reference it in to_ruby
Rice::Class rb_cRootContext;

template <>
Rice::Object to_ruby<MySqlParser::RootContext*>(MySqlParser::RootContext* const &x)
{
  if (!x) return Rice::Nil;
  return Rice::Data_Object<MySqlParser::RootContext>(x, rb_cRootContext, nullptr, nullptr);
} 

...
// In your Init_
  rb_cRootContext = rb_mMySqlParser
    .define_class<MySqlParser::RootContext>("RootContext")
   //...
```

The important parts here are the `nullptr` passed into the 3rd and 4th parameters. Those are the `mark` and `free` methods for registering this object with Ruby's GC, respectively, passing in NULL (or 0) disables registering this object with the GC so it won't get cleaned up underneath ANTLR.

**Comment by camertron** [comment]
@jasonroelofs awesome, setting `mark` and `free` to `nullptr` seems to have fixed the problem, thank you! I ended up having to apply your fix to a bunch of the ANTLR C++ classes to avoid segfaults and pushed everything up to my repo. The extra code is straightforward enough, but I do sort of wonder if memory is getting cleaned up correctly. It's hard to be sure.

As requested here's [a gist](https://gist.github.com/camertron/c47163e376b4381321f571eaf8848489) of the full segfault stack trace.

**Comment by jasonroelofs** [comment]
Glad we could get that fixed for you, and the stack trace shows that it's Rice's clean-up that's throwing the segfault (for the same reason just in reverse):

```
4   mysql_parser.bundle                 0x000000010bd7d21d _ZN4Rice21Default_Free_FunctionIN11MySqlParser11RootContextEE4freeEPS2_ + 13
```

Memory management is a hard problem, and it's doubly hard when you're trying to combine two very different memory systems. I can't claim that Rice has a perfect memory strategy, more that it provides ways to get around the obvious problems. At the top level the rule should be: if Rice or Ruby create the object, they should clean it up. Otherwise you have to make sure Rice doesn't.
