### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by uvlad7** [jasonroelofs/rice#175]
Hi, I don't want to create like a million of issues but I really need your help to understand how to work with the library. I'm not good enough at C++ to find the answers in the sources.

1. Does `return Rice::detail::To_Ruby<MyClass>().convert(my_class_instance)` always have the same result as `return my_class_instance`? I mean, is this how `my_class_instance` is converted under the hood?
2. The same about arguments. Is `Rice::detail::From_Ruby<MyOrStdClass>().convert(value)` used?
3. How to check types of arguments in the same way as automatic conversion does? Call `Data_Type<MyOrStdClass>::is_descendant(value)` and `detail::unwrap<MyOrStdClass>(value, Data_Type<T>::rb_type())` if the result is true?
4. Is it possible to mark `yield`ed values in the same way `Return().keepAlive()` does? I implemented [this method](https://github.com/uvlad7/ruby-jsoncons/blob/ea30aa3af899eb4baae6c73050997d60aed031c5/ext/jsoncons/jsoncons.cpp#L126) using `keepAlive` and I want to implement an iterator using the same feature.
5. Is it possible to wrap `rb_yield_values` or `rb_yield_values2` with `detail::protect`?
6. Are `return`, `break`, `next` safe with implementation like [this](https://github.com/uvlad7/ruby-jsoncons/blob/7e3664ac0e65ba7b7f326abc374a36939e9f5f50/ext/jsoncons/jsoncons.cpp#L213)?
7. Is [this comment](https://github.com/jasonroelofs/rice/blob/master/include/rice/rice.hpp#L7133) still true? As far as I understand, detail::To_Ruby uses it for wrapped classes and it doesn't care if pointers are equal. And the documentation [says](https://jasonroelofs.com/rice/4.x/advanced/functions.html#return-values) it's OK.
8. Is it possible to return a `Rice::Array` and mark its elements like `Return().keepAlive()` marks a single return value?

**Comment by jasonroelofs** [comment]
> Does return Rice::detail::To_Ruby<MyClass>().convert(my_class_instance) always have the same result as return my_class_instance? I mean, is this how my_class_instance is converted under the hood?

> The same about arguments. Is Rice::detail::From_Ruby<MyOrStdClass>().convert(value) used? 

If I understand this question, you kind of found the answer to this in a later question. Ruby objects keep an internal pointer to the C++ object they are wrapping, but multiple Ruby objects can wrap the same C++ object. It would be quite expensive to try to map the Ruby side of things 1-to-1.

> How to check types of arguments in the same way as automatic conversion does? Call Data_Type<MyOrStdClass>::is_descendant(value) and detail::unwrap<MyOrStdClass>(value, Data_Type<T>::rb_type()) if the result is true?

Can you provide more info on what you're trying to do here?

> Is it possible to mark yielded values in the same way Return().keepAlive() does? I implemented [this method](https://github.com/uvlad7/ruby-jsoncons/blob/ea30aa3af899eb4baae6c73050997d60aed031c5/ext/jsoncons/jsoncons.cpp#L126) using keepAlive and I want to implement an iterator using the same feature.

The keepAlive is about tracking objects that are created on one side and sent to the other without any other tracking. Could you provide more details on where using `yield` may cause a crash due to an object getting GC'd early?

> Is it possible to wrap rb_yield_values or rb_yield_values2 with detail::protect?

Yes, to be safe you should always wrap Ruby C-API calls with `protect`. Did you run into a situation where this didn't do what you expected?

> Are return, break, next safe with implementation like [this](https://github.com/uvlad7/ruby-jsoncons/blob/7e3664ac0e65ba7b7f326abc374a36939e9f5f50/ext/jsoncons/jsoncons.cpp#L213)?

That is a good question. I'm not sure what will happen. Please give it a try and let me know if you run into weird effects or crashes and we can look more into it.

> Is [this comment](https://github.com/jasonroelofs/rice/blob/master/include/rice/rice.hpp#L7133) still true? As far as I understand, detail::To_Ruby uses it for wrapped classes and it doesn't care if pointers are equal. And the documentation [says](https://jasonroelofs.com/rice/4.x/advanced/functions.html#return-values) it's OK.

Yes this is all true.

> Is it possible to return a Rice::Array and mark its elements like Return().keepAlive() marks a single return value?

I don't think this is necessary? By the nature of being in an Array, all items in the array will get marked when the array itself gets marked. Did you run into an issue that implies this isn't happening?

**Comment by uvlad7** [comment]
Well, about 1. and 2. - I kind of found the answer. I needed to confirm if I was right, but then I dug deeper into the sources and found in `NativeFunction<Function_T, IsMethod>::operator()` that it was true. The same about 3. - I found that all types are converted with `From_Ruby<T>().convert` and that its default implementation uses `Data_Object::from_ruby`, which performs `is_descendant` check. Well, now I understand, that if I want to accept arguments of different types, I have to implement the checks myself, like [here](https://github.com/uvlad7/ruby-jsoncons/blob/feature_each/ext/jsoncons/jsoncons.cpp#L35), since all `Data_Object` methods only work for bound types.

4. Well, yielded values can become a [return value](https://github.com/uvlad7/ruby-jsoncons/blob/feature_each/test/jsoncons_test.rb#L74). In that test I only [implemented](https://github.com/uvlad7/ruby-jsoncons/blob/feature_each/ext/jsoncons/jsoncons.cpp#L208) `each` method, `to_a` comes from `Enumerable`, but user can implement it yourself or store yielded values somehow else. And when I forgot to add `keepAlive` to `[]` method, it [crashed](https://github.com/uvlad7/ruby-jsoncons/blob/feature_each/test/jsoncons_test.rb#L60)

**Comment by uvlad7** [comment]
5 - I know these calls must be `protect`ed, I just don't know how to do that. It looks like I've found a solution for `rb_yield_values2`, but I still don't understand how to call `rb_yield_values`.
```
VALUE values[2] = {key_value, value_value};
detail::protect<VALUE, int, const VALUE *>(rb_yield_values2, 2, values);
```

**Comment by uvlad7** [comment]
7 That is, it only applies to `Data_Object(T* obj, bool isOwner = false, Class klass = Data_Type<T>::klass());`, not `Data_Object(T& obj, bool isOwner = false, Class klass = Data_Type<T>::klass());`?

**Comment by uvlad7** [comment]
8 Sorry, my description was not clear. As far as understand, `Arg& keepAlive()` allows us to keep the argument alive untill `self` is alive, and not vise versa. But `Return& keepAlive()` keeps `self` alive as long as the return value is alive (and actually I find it quite confusing). But this is what I need in my `at` [method](https://github.com/uvlad7/ruby-jsoncons/blob/feature_to_a/ext/jsoncons/jsoncons.cpp#L126). But I also want to implement `to_a` methods (here is my attempts [1](https://github.com/uvlad7/ruby-jsoncons/blob/feature_to_a/ext/jsoncons/jsoncons.cpp#L126), [2](https://github.com/uvlad7/ruby-jsoncons/blob/feature_to_a/ext/jsoncons/jsoncons.cpp#L126), ignore WTFs, I've already found this happens because `data` is not actually garbage collected if it was recently accessed). So, to safely return an array of values, I need to keep `self` alive while at least one of them is alive. So yes, I ran into an issue. I don't understand why, but the program [doesn't just crash](https://github.com/uvlad7/ruby-jsoncons/blob/feature_to_a/ext/jsoncons/jsoncons.cpp#L251) when `data` is GCed, as is the case with `at` without `Return().keepAlive()`. But it still doesn't work properly.

**Comment by cfis** [comment]
Um, a lot of stuff up above. 

Your understanding of keepAlive is correct. But I don't understand the question you are asking and what isn't working properly. If you still need help, then maybe you can clarify your question?

**Comment by uvlad7** [comment]
Yep, I still need help. I have a custom json class with an `at` method. As long as it does't copy the internal data, I use `Return().keepAlive()` in it. But what if I want to implement `each` and `to_a` methods? In both cases all `yield`-ed/`return`-ed elements can be stored somewhere and I need to bind the lifetime of `self` to all of them.

**Comment by cfis** [comment]
5. rb_yield_values2 should be ok (works for me, but I have been tweaking code). Not sure about rb_yield_values. Its defined as:

```
VALUE rb_yield_values(int n, ...);
```

The C version of a variable number of arguments. Haven't had luck matching that with a C++ template (there is probably some way to do it, but I don't know what it is). But rb_yield_values2  should be good enough to use.

7. The link doesn't point to a comment anymore. But if you are asking can a single C++ object be wrapped by multiple Ruby objects, then yes that can and does happen. Of course it only works if C++ code owns the object and not Ruby (otherwise one of the Ruby objects will free the C++ object which would then cause a crash for the other Rub objects). Enforcing a 1 to 1 mapping between C++ and Ruby objects would require keeping track of all C++ object and their Ruby counterparts. Doable but not sure it is worth it.

Right now I don't think its possible for a each method to either yield a value or return an enumerator. In the yield case, the each method at the end returns the object itself (usually a C++ object). So the function either can return a VALUE or a C++ object. One way to do that is via std::variant but Rice doesn't support it yet (I have some rough code that partially does).

**Comment by cfis** [comment]
This commit (https://github.com/jasonroelofs/rice/commit/cb84496195f74858a24f2d6706423b64148168bf) enables using rb_yield_values. An example of using rb_yield_values2  is at https://github.com/jasonroelofs/rice/blob/master/rice/stl/map.ipp#L184. rb_yield_values also works fine there too (I tested it, but think is probably the better API to use).

**Comment by cfis** [comment]
@uvlad7  - That took a lot of changes, but latest updates to Rice support enumerators. See documentation at https://github.com/jasonroelofs/rice/blob/master/doc/advanced/enumerators.rst.

I'm going to close this issue. If you have other issues you want to bring up, feel free to open additional tickets.

**Comment by uvlad7** [comment]
Cool!
