### ISSUE TITLE
`std::string_view` support

### ISSUE THREAD

**Issue by Bo98** [jasonroelofs/rice#196]
Wrappers like `Rice::String` currently require you to pass `std::string` when it seems that a `std::string_view` could work. Currently, you have to copy any `std::string_view` to a `std::string` only for it to be copied again to a Ruby string - avoiding the double copy by changing the signature to `std::string_view` (which `std::string` can implicitly convert to) would be useful.

https://github.com/jasonroelofs/rice/blob/d4a1f7562d2f791f798ef47fa0d92f07862d8aed/rice/cpp_api/String.ipp#L19

Equally, the ability to create a `std::string_view` from an existing `Rice::String` could be useful to further avoid more copies.

**Comment by jasonroelofs** [comment]
We can probably do something along these lines. I'll take a look.

**Comment by jasonroelofs** [comment]
Doing some more reading into what `string_view` is meant for and looking into how we could use it in Rice, I'm not comfortable adding it to the core at this time. For most cases in Rice, we'd have to convert the `string_view` into a `string` to safely pass it into the Ruby CAPI anyway. 

I'd be curious to know if the extra String allocations you're seeing are a significant bottleneck.

**Comment by cfis** [comment]
Seems like there are 3 things here.

----
First, pass a `std::string_view` to a `Rice::String`. So add this code:

```
 inline String::String(std::string_view s) : Builtin_Object<T_STRING>(detail::protect(rb_str_new, s.data(), (long)s.length())) 
```

The advantage of that, as mentioned by @Bo98, is that is avoids an extra copy. To me that looks safe since `rb_str_new` is going to immediately copy the passed in string. However, @jasonroelofs you had misgiving on doing this?

Note we could get rid of the `std::string const&` constructor, but I'd probably just leave it (seems clearer to me).

---

Second, retrieve a `std::string_view` from a a `Rice::String`.  So this code:

``` 
  inline std::string_view String::str_view() const
  {
    return std::string_view(RSTRING_PTR(value(), RSTRING_LEN(value()));
  }
```
That isn't any more or less safe than the existing `c_str()` method that returns a pointer to a Ruby string. Once a GC happens, the references Ruby string could be GCed or moved via compaction therefore making the pointer invalid.

This seems less important to me since you can always create a std::string_view from a `*char` and thus can use the `c_str` method. But I'm fine with adding it also.

----------

Third, Rice should be able to call C++ methods that take a std::string_view as a function parameter. You an support this manually today be using `define_class<std::string_view>` but since it a standard stl class it should be added to Rice's stl support. So I'll at least do that.

**Comment by cfis** [comment]
Should be fixed by #196. I also did add support for creating a Rice::String from a std::string_view. See what you think (and hope that is ok @jasonroelofs ).

**Comment by jasonroelofs** [comment]
Yeah those changes look good, thanks for jumping into this, though not sure if they work yet or not. I wonder if there's a better way to ensure that the combined header files get created. Right now `rake` fails to build on `master`, can you take a look?

**Comment by cfis** [comment]
Yup. Was going to get all tests passing and then ping you about creating a new release.
