### ISSUE TITLE
Please use Markdown + backticks in your README

### ISSUE THREAD

**Issue by adamski** [jasonroelofs/rice#83]
Please use the Github standard backticks \`\`\` for enclosing code sections - will make your docs much more readable! 
 You can do also do e.g. \`\`\`ruby or \`\`\`cpp for language specific syntax highlighting...

**Comment by jasonroelofs** [comment]
The documentation is written in Doxygen and as there is quite a lot of it I do not currently plan on reformatting it any time soon. I would recommend reading the generated documentation available here: http://jasonroelofs.github.io/rice/ which does provide syntax highlighting.

**Comment by adamski** [comment]
OK thanks for clarification, no problem

**Comment by lexruee** [comment]
@jasonroelofs What about a github friendly README.md?

Because I assume lot of people first find the github repository and not the http://jasonroelofs.github.io/rice website. 

Having a short readme written in markdown would be more user friendly. This could be an entry point to show a simple hello world example and an additional link to the rice documentation http://jasonroelofs.github.io/rice/ where more information can be found.

What do you think?

**Comment by jasonroelofs** [comment]
Sorry for the delay. It's not a bad idea, I'll think about it. Thanks for the feedback!
