### ISSUE TITLE
Incorrect $RICE_PREFIX when installed via bundler

### ISSUE THREAD

**Issue by gravitystorm** [jasonroelofs/rice#86]
When I install rice 1.7.0 via bundler (i.e. `bundle install` where the Gemfile contains `rice`) then the $RICE_PREFIX in ruby/lib/mkmf-rice.rb is incorrect:

```
 grep "RICE_PREFIX =" /var/lib/gems/2.1.0/gems/rice-1.7.0/ruby/lib/mkmf-rice.rb
  $RICE_PREFIX = "/tmp/bundler20150625-3815-h5yg1drice-1.7.0/gems/rice-1.7.0/ruby/lib"
```
When I install it using `gem install rice`, then the prefix is correct:

```
 grep "RICE_PREFIX =" /var/lib/gems/2.1.0/gems/rice-1.7.0/ruby/lib/mkmf-rice.rb
  $RICE_PREFIX = "/var/lib/gems/2.1.0/gems/rice-1.7.0/ruby/lib"
```

I assume bundler must behave differently, by copying the gem into location after the compilation is complete.

Do you have any advice?

Could $RICE_PREFIX be determined when the ruby code runs, rather than during the gem installation? I guess it's also not robust to e.g. bundle install --deployment followed by a directory rename.

**Comment by jasonroelofs** [comment]
That is strange, I had not yet tried installing Rice via bundler and that's weird that it picks up a tmp file like that. I'll have to look and see what bundler is doing and what we can do about this.

**Comment by gravitystorm** [comment]
I forgot to say on my original report that I tried this with both Ubuntu 14.04 and Ubuntu 15.04, and using both the packaged bundler (`apt-get install bundler`) and using upstream bundler via rubygems (`gem install bundler`) so a wide range of bundler versions were tried. Do let me know if you can't reproduce it though, happy to help.

**Comment by jasonroelofs** [comment]
Looking into this, I don't see any reason why mkmf-rice.rb shouldn't just calculate that itself, so I'll probably just do that. You're right though, it's very explicitly a "bundler installing gems to the system-level rubygems". Specifically, `bundler` tries very hard not to use `sudo` so it sets up a tmp dir to build any gems before moving them into the correct install location. Otherwise, every other bundle and gem install builds the gem in place.
